### ISSUE TITLE
Remove `setuptools` dependency

### ISSUE THREAD

**Issue by aeisenbarth** [magmax/python-readchar#116]
I could be mistaken, but to me it seems `python-readchar` should not specify `setuptools` as install requirement. Typically it is provided by the environment, or specified as build requirement. It is never imported and used in order to run readchar.

As a consequence, a specific version of `setuptools` leaks into my lock files and I have to specifically exclude it.

See also https://github.com/magmax/python-readchar/issues/111. In pyproject.toml, there would be:
```toml
[build-system]
requires = ["setuptools", "wheel"]

[project]
dependencies = [
]
```
